---
deployment:
  tasks:
    - export DEPLOYPATH=/home/plantei5/plantrip-backend-laravel
    - /bin/cp -R $DEPLOYPATH /home/plantei5/plantrip-backend-laravel
    - export PATH=$PATH:/usr/local/bin
    - cd $DEPLOYPATH
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan migrate --force
    - php artisan optimize
